- hosts: datanodes
  tasks:
        - file:
            path: "/datanode"
            state: "directory"
        
       
        - copy:
            src: "/home/hadoop_cluster/hdfs-site_datanode.xml"
            dest: "/etc/hadoop/hdfs-site.xml"
            owner: "root"
            group: "root"
            mode: "0644"
      
        - copy:
            src: "/home/hadoop_cluster/core-site.xml"
            dest: "/etc/hadoop/"
            owner: "root"
            group: "root"
            mode: "0644"
